import './globals.css'
import { Box } from '@mui/material'
import Image from 'next/image'
import type { Metadata } from 'next'
import ThemeRegistry from './ThemeRegistry'

export const metadata: Metadata = {
  title: "Rick and Morty | Conexa",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Box sx={{ position: 'relative', minHeight: '100vh', overflow: 'hidden' }}>
            <Box
              sx={{
                position: 'absolute',
                inset: 0,
                zIndex: 0,
                filter: 'blur(2px)',
                transform: 'scale(1.05)',
              }}
            >
              <Image
                src="/assets/images/bg.png"
                alt="Fondo"
                fill
                priority
                style={{ objectFit: 'cover' }}
              />
            </Box>
            <Box
              sx={{
                position: 'absolute',
                inset: 0,
                backgroundColor: 'rgba(0, 0, 0, 0.4)',
                zIndex: 1,
              }}
            />
            <Box
              sx={{
                position: 'relative',
                zIndex: 2,
                color: '#fff',
                minHeight: '100vh',
              }}
            >
              {children}
            </Box>
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
}
